FROM golang:latest

ENV GO111MODULE=auto
RUN go get github.com/gorilla/mux
RUN go get github.com/dgrijalva/jwt-go
RUN go get go.mongodb.org/mongo-driver/mongo
RUN go get github.com/google/uuid
RUN go get golang.org/x/crypto/bcrypt

RUN mkdir /app
ADD . /app/
WORKDIR /app

RUN go build -o main main.go

CMD ["/app/main"]

EXPOSE 8080