version : "3.3"

services:

  aut_server:
    container_name: auth_server
    image: go-auth-server:latest
    environment:
      SERVER_PORT: 8080
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    ports:
    - 8080:8080
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - 27017:27017

